### ISSUE TITLE
Run grid search for comparison methods

### ISSUE THREAD

**Issue by sampolk** [sampolk/DiffusionLearning-INTEGRAL#2]
Right now, we are only running coarse grid searches on the parameters of the other algorithms. We should run the following grid searches for all other algorithms (on all benchmark datasets). 

- [ ] DBSCAN with Epsilon = prctile(`dNN`, k), where `k=0:100` and `dNN(i)` is the distance between `X(i,:)` and that point's `i`th nearest neighbor. 
- [ ] Spectral Clustering with the same graph grid search as our M-LUND grid search (See issue #1). 
- [ ] SC-I with the same graph grid search as our M-LUND grid search (See issue #1). This may require modifying the existing code for SC-I. 
- [ ] Fast ESC  with the same graph grid search as our M-LUND grid search (See issue #1). This may require modifying the existing code for Fast ESC. 
- [ ] KNN SSC with alpha ranging `0:0.01:1`  and `N` ranging the same values used for M-LUND (See issue #1 ).

**Comment by sampolk** [comment]
Small update on SC-I. I have modified the code for SC-I to be able to run with arbitrary weight matrices. This includes those which we are using in our M-LUND analysis. As such, I think we now can run SC-I comparisons in the same way we run SC comparisons. The new file is called `SCiGeneral.m`.
